[package]
name = "boruta-fru"
version = "0.1.0"
authors = ["Krzysztof Piwonski <borutaarrow@kpiwonski.com>", "Miron B. Kursa <m@mbq.me>"]
edition="2024"
license = "GPL-3.0-or-later"

[dependencies]
fru-arrow = "0.1.1"
minarrow = {version="0.16.2", features=["scalar_type"]}
xrf = "0.1.7"

[dev-dependencies]
float-cmp = "0.10.0"
